version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.2
    # image: wodby/mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  php:
    # image: wodby/wordpress-php:7.2
    # image: wodby/wordpress-php:7.1
    # image: wodby/wordpress-php:7.0
    # image: wodby/wordpress-php:5.6
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
     - ./:/var/www/html:cached # Docker-sync for macOS users

  # nginx:
  #   image: wodby/wordpress-nginx:4-1.13
  # # image: wodby/wordpress-nginx:4-1.12
  #   depends_on:
  #     - php
  #   environment:
  #     NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
  #     NGINX_ERROR_LOG_LEVEL: debug
  #     NGINX_BACKEND_HOST: php
  #     NGINX_SERVER_ROOT: /var/www/html/web
  #   volumes_from:
  #     - php
  #   labels:
  #     - 'traefik.backend=${TRAEFIK_HOST}_nginx_1'
  #     - 'traefik.port=80'
  #     - 'traefik.frontend.rule=Host:${TRAEFIK_HOST}.test'

  # apache:
  #   image: wodby/php-apache:2.4
  #   depends_on:
  #     - php
  #   environment:
  #     APACHE_LOG_LEVEL: debug
  #     APACHE_BACKEND_HOST: php
  #     APACHE_SERVER_ROOT: /var/www/html/web
  #   volumes_from:
  #    - php
  #   labels:
  #     - 'traefik.backend=${TRAEFIK_HOST}_apache_1'
  #     - 'traefik.port=80'
  #     - 'traefik.frontend.rule=Host:${TRAEFIK_HOST}.test'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=${TRAEFIK_HOST}_mailhog_1'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.${TRAEFIK_HOST}.test'
