version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.2
    # image: wodby/mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

  php:
# 1. Images without Drupal – wodby/drupal-php:[PHP_VERSION]-[STABILITY_TAG].
#    image: wodby/drupal-php:7.1-3.3.1
#    image: wodby/drupal-php:7.0-3.3.1
#    image: wodby/drupal-php:5.6-3.3.1
#    image: wodby/drupal-php:5.3-3.3.1
# 2. Images without Drupal – wodby/drupal-php:[PHP_VERSION]-[STABILITY_TAG]. Version for development (--enable-debug)
#    image: wodby/drupal-php:7.1-dev-3.3.1
#    image: wodby/drupal-php:7.0-dev-3.3.1
#    image: wodby/drupal-php:5.6-dev-3.3.1
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: ${DATABASE_HOST}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
      DB_DRIVER: mysql
      PHP_IDE_CONFIG: serverName=Docker
    volumes:
     - ./:/var/www/html:nocopy # Docker-sync for macOS users

  # nginx:
  #   # wodby/drupal-nginx:[DRUPAL_VERSION]-[NGINX_VERSION]-[STABILITY_TAG].
  #   # image: wodby/drupal-nginx:8-1.13-3.0.2
  #   # image: wodby/drupal-nginx:7-1.13-3.0.2
  #   # image: wodby/drupal-nginx:6-1.13-3.0.2
  #   # image: wodby/drupal-nginx:8-1.12-3.0.2
  #   # image: wodby/drupal-nginx:7-1.12-3.0.2
  #   # image: wodby/drupal-nginx:6-1.12-3.0.2
  #   depends_on:
  #     - php
  #   environment:
  #     NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
  #     NGINX_ERROR_LOG_LEVEL: debug
  #     NGINX_BACKEND_HOST: php
  #     NGINX_SERVER_ROOT: /var/www/html/web
  #   volumes_from:
  #     - php
  #   labels:
  #     - 'traefik.backend=${TRAEFIK_HOST}_nginx_1'
  #     - 'traefik.port=80'
  #     - 'traefik.frontend.rule=Host:${TRAEFIK_HOST}.test'

  # apache:
  #   # wodby/drupal-nginx:[DRUPAL_VERSION]-[NGINX_VERSION]-[STABILITY_TAG].
  #   image: wodby/php-apache:2.4
  #   depends_on:
  #     - php
  #   environment:
  #     APACHE_LOG_LEVEL: debug
  #     APACHE_BACKEND_HOST: php
  #     APACHE_SERVER_ROOT: /var/www/html/www
  #   volumes_from:
  #     - php
  #   labels:
  #     - 'traefik.backend=${TRAEFIK_HOST}_apache_1'
  #     - 'traefik.port=80'
  #     - 'traefik.frontend.rule=Host:${TRAEFIK_HOST}.test'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=${TRAEFIK_HOST}_mailhog_1'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.${TRAEFIK_HOST}.test'
